import { inject, Injectable, Signal } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';
import { toSignal } from '@angular/core/rxjs-interop';

export interface TranslatedValueOptions {
  'MENU_HEADER_OPTION.CLIENT': string;
  'MENU_HEADER_OPTION.CLIENT_CREATE_CLIENT': string;
  'MENU_HEADER_OPTION.CLIENT_LIST_CLIENTS': string;
  'MENU_HEADER_OPTION.HOME': string;
  MENU_SIDE_OPTION_LIST_CLIENTS: string;
  MENU_SIDE_OPTION_CREATE_CLIENT: string;
  CLIENT_LIST_TOOLBAR_BUTTON_CREATE_CLIENT: string;
  CLIENT_LIST_TOOLBAR_BUTTON_CARD_VIEW: string;
  CLIENT_LIST_TOOLBAR_BUTTON_TABLE_VIEW: string;
  CLIENT_LIST_TOOLBAR_SEARCH_INPUT: string;
  CLIENT_LIST_ACTION_EDIT: string;
  CLIENT_LIST_ACTION_DELETE: string;
  CLIENT_FORM_PERSONAL_INFORMATION: string;
  CLIENT_FORM_ADDRESS_INFORMATION: string;
  CLIENT_FORM_BUTTON_SUBMIT: string;
  MESSAGE_CLIENT_CREATED_SUCCESS: string;
  MESSAGE_SUMMARY_CLIENT_CREATED_SUCCESS: string;
  MESSAGE_CLIENT_CREATED_ERROR: string;
  MESSAGE_SUMMARY_CLIENT_CREATED_ERROR: string;
  MESSAGE_CLIENT_UPDATED_SUCCESS: string;
  MESSAGE_SUMMARY_CLIENT_UPDATED_SUCCESS: string;
  MESSAGE_CLIENT_UPDATED_ERROR: string;
  MESSAGE_SUMMARY_CLIENT_UPDATED_ERROR: string;
  MESSAGE_CLIENT_DELETE_SUCCESS: string;
  MESSAGE_SUMMARY_CLIENT_DELETE_SUCCESS: string;
  MESSAGE_CLIENT_DELETE_ERROR: string;
  MESSAGE_SUMMARY_CLIENT_DELETE_ERROR: string;
  DELETE_CLIENT_BUTTON_CONFIRM: string;
  DELETE_CLIENT_BUTTON_CANCEL: string;
  DELETE_CLIENT_HEADER: string;
  DELETE_CLIENT_MESSAGE: string;
}

@Injectable({
  providedIn: 'root',
})
export class TranslatedValuesService {
  private readonly translate = inject(TranslateService);
  readonly translatedTextPage: Signal<TranslatedValueOptions | null> =
    toSignal<TranslatedValueOptions>(
      this.translate.get([
        'MENU_HEADER_OPTION.CLIENT',
        'MENU_HEADER_OPTION.CLIENT_CREATE_CLIENT',
        'MENU_HEADER_OPTION.CLIENT_LIST_CLIENTS',
        'MENU_HEADER_OPTION.HOME',
        'MENU_SIDE_OPTION_CREATE_CLIENT',
        'MENU_SIDE_OPTION_LIST_CLIENTS',
        'MENU_SIDE_OPTION_CREATE_CLIENT',
        'MENU_SIDE_OPTION_LIST_CLIENTS',
        'CLIENT_LIST_TOOLBAR_BUTTON_CREATE_CLIENT',
        'CLIENT_LIST_TOOLBAR_BUTTON_CARD_VIEW',
        'CLIENT_LIST_TOOLBAR_BUTTON_TABLE_VIEW',
        'CLIENT_LIST_TOOLBAR_SEARCH_INPUT',
        'CLIENT_LIST_ACTION_EDIT',
        'CLIENT_LIST_ACTION_DELETE',
        'CLIENT_FORM_PERSONAL_INFORMATION',
        'CLIENT_FORM_ADDRESS_INFORMATION',
        'CLIENT_FORM_BUTTON_SUBMIT',
        'MESSAGE_CLIENT_CREATED_SUCCESS',
        'MESSAGE_SUMMARY_CLIENT_CREATED_SUCCESS',
        'MESSAGE_CLIENT_CREATED_ERROR',
        'MESSAGE_SUMMARY_CLIENT_CREATED_ERROR',
        'MESSAGE_CLIENT_UPDATED_SUCCESS',
        'MESSAGE_SUMMARY_CLIENT_UPDATED_SUCCESS',
        'MESSAGE_CLIENT_UPDATED_ERROR',
        'MESSAGE_SUMMARY_CLIENT_UPDATED_ERROR',
        'MESSAGE_CLIENT_DELETE_SUCCESS',
        'MESSAGE_SUMMARY_CLIENT_DELETE_SUCCESS',
        'MESSAGE_CLIENT_DELETE_ERROR',
        'MESSAGE_SUMMARY_CLIENT_DELETE_ERROR',
        'DELETE_CLIENT_BUTTON_CONFIRM',
        'DELETE_CLIENT_BUTTON_CANCEL',
        'DELETE_CLIENT_HEADER',
        'DELETE_CLIENT_MESSAGE',
      ]),
      { initialValue: null },
    );
}
